class TeamsController < ApplicationController
  def start; end

  def new
    @team_a, @team_b = Array.new(16) { Team.new }.each_slice(8).to_a
    flash.now[:message] = 'The team division is already established !!!' if Team.exists?
  end

  def draw_teams
    @teams = Team.all
  end

  def autogenerate_divisions
    Team.autogenerate_division
    redirect_to draw_teams_path, notice: 'Divisions have been successfully autogenerated.'
  end

  def generate_divisions
    team_params[:teams_attributes].each_value { |team_attributes| Team.create(team_attributes) }
    redirect_to draw_teams_path, notice: 'Divisions have been successfully created.'
  end

  def team_params
    params.require(:team).permit(teams_attributes: %i[name division])
  end
end
